### ISSUE TITLE
towards "boot.rs"

### ISSUE THREAD

**Issue by hawkw** [hawkw/sos-kernel#17]
Now that [naked functions are a thing](https://github.com/rust-lang/rfcs/pull/1201#issuecomment-198505381), we can potentially start transitioning some code out of the asm boot files into Rust-land. 

This isn't terribly important - the current asm works fine.

Requires:
- [x] Implement Multiboot header in pure Rust (#48)
- [x] Implement page-table mapping in pure Rust (#67)
- [x] Set control register flags from Rust (#68)
- [x] Figure out how to get Cargo to build & link the 32-bit boot module (#69)
